const messageTypes = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  VOICE: 'VOICE',
  VIDEO: 'VIDEO',
  OPTION: 'OPTION',
  CATALOGUE: 'CATALOGUE',
  END_CALL: 'END_CALL',
  PERSONALIZE_TEXT: 'PERSONALIZE_TEXT',
  RECORD: 'RECORD',
  CSR: 'CSR',
  FORWARD_TO_AGENT: 'FORWARD_TO_AGENT',
};

export default messageTypes;
