const {
  PORT,
  MONGO_HOST,
  MONGO_PORT,
  MONGO_DATABASE,
  MONGO_USERNAME,
  MONGO_PASSWORD,

  JWT_SECRET_KEY,
  JWT_EXPIRES_TIME,
  CLIENT_SECRET,
  CLIENT_ID,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  API_DOMAIN_ASR,
  API_DOMAIN_SLU,
} = process.env;

const { A_WEEK } = require('../constants');

module.exports = {
  PORT: PORT || 3000,
  MONGO_URI: `mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}`,
  JWT_SECRET_KEY,
  JWT_EXPIRES_TIME: parseInt(JWT_EXPIRES_TIME, 10) || A_WEEK,
  CLIENT_SECRET,
  CLIENT_ID,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  API_DOMAIN_ASR,
  API_DOMAIN_SLU,
};
