export default {
  HOME: '/home',
  SUB_CAMPAIGN: `/home/sub-campaign/:type`,
  SEARCH_CAMPAIGN: '/search-campaign',
  CHATBOT: '/home/:campaignId/chatbot',
  INFO_USER: '/info-user',
  RESULT_USER: '/:campaignId/result-user',
  INFO_CAMPAIGN: '/home/:campaignId/info-campaign',
  CREATE_CAMPAIGN: '/campaign/:pageType/:step',
  EDIT_CAMPAIGN: '/campaign/:campaignId/:pageType/:step',
  VIEW_CAMPAIGN: '/campaign-view/:campaignId/:pageType',
  CAMPAIGN_MANAGE: '/campaign-manage',
  USER_MANAGE: '/user-manage',
  OVERVIEW: '/overview',
  REPORT: '/report',
  SLU_LANDING_PAGE: '/slu/home',
  SLU_ROOM: '/slu/room/:roomId',
  SLU_SOLO: '/slu/solo/record',
  SLU_REPORT: '/slu-report',
  ASR: '/asr',
  // CHATROOM: '/asr/chatroom/0/:chatroomID?accessToken=:accessToken',
  CHATROOM: '/asr/chatroom/0/:chatroomID',
  IMPORT_AUDIO: '/importAudio',
  VALIDATE_DATA: '/validateData',
  AUDIO_MANAGE: '/audio-manage',
  YOUR_CAMPAIGN_OVERVIEW: '/your-campaign-overview',
};
